### PR TITLE
[French translation] Better grammar and phrases

### PR DESCRIPTION
**Pull request by Niilyx**
but i don't understand the "i use arch btw" on line 170

### CODE REVIEW

**Comment by FlorianLeChat** [comment]
https://github.com/WilliamVenner/gmpublisher/pull/15/files#diff-849e3fab5f8f13d7147af2a08e45ac75945b75506dae850ca68d942a3c34c142R181-R189

I skipped the translation for these sentences because the tags themselves of the Workshop are not translated to avoid misunderstandings.

> but i don't understand the "i use arch btw" on line 170

https://github.com/WilliamVenner/gmpublisher/pull/12#issuecomment-826100417

**Comment by WilliamVenner** [comment]
please stop starting civil wars

**Comment by Niilyx** [comment]
> https://github.com/WilliamVenner/gmpublisher/pull/15/files#diff-849e3fab5f8f13d7147af2a08e45ac75945b75506dae850ca68d942a3c34c142R181-R189
> 
> I skipped the translation for these sentences because the tags themselves of the Workshop are not translated to avoid misunderstandings.
> 
> > but i don't understand the "i use arch btw" on line 170
> 
> [#12 (comment)](https://github.com/WilliamVenner/gmpublisher/pull/12#issuecomment-826100417)

I know, I avoided tags such as scenic, fun etc... but some sentences didn't seem good. I just corrected them. As for the tags I translated, they are in the game as well...

> please stop starting civil wars

Haha no problem, all cool here :)

**Comment by R4K0** [comment]
> please stop starting civil wars

of course it happened under French translation

**Pull request merged**
